version: '3'

services:
  money-transaction:
    container_name: money-transaction
    image: 'vadimstepuro/money-transaction:latest'
    ports:
      - '8080:8080'
    environment:
      KAFKA_SERVER: "kafka:29092"
      DB_HOST: "db:5432"
    networks:
      - money

networks:
  money:
    name: money
    external: true